# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memory.ui'
#
# Created by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(344, 323)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label1 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label1.setFrameShadow(QtGui.QFrame.Sunken)
        self.label1.setText(_fromUtf8(""))
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.gridLayout.addWidget(self.label1, 3, 0, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.btn_new = QtGui.QPushButton(Dialog)
        self.btn_new.setObjectName(_fromUtf8("btn_new"))
        self.gridLayout.addWidget(self.btn_new, 2, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_19 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtGui.QFrame.Box)
        self.label_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 3, 3, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtGui.QFrame.Box)
        self.label_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtGui.QFrame.Box)
        self.label_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_25 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setFrameShape(QtGui.QFrame.Box)
        self.label_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 5, 0, 1, 1)
        self.label_17 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setFrameShape(QtGui.QFrame.Box)
        self.label_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_27 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setFrameShape(QtGui.QFrame.Box)
        self.label_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 5, 3, 1, 1)
        self.label_29 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setFrameShape(QtGui.QFrame.Box)
        self.label_29.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 6, 0, 1, 1)
        self.label_31 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setFrameShape(QtGui.QFrame.Box)
        self.label_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 6, 3, 1, 1)
        self.label_21 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setFrameShape(QtGui.QFrame.Box)
        self.label_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 4, 0, 1, 1)
        self.label_15 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setFrameShape(QtGui.QFrame.Box)
        self.label_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 2, 3, 1, 1)
        self.label_11 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtGui.QFrame.Box)
        self.label_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 3, 1, 1)
        self.label_23 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setFrameShape(QtGui.QFrame.Box)
        self.label_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 4, 3, 1, 1)
        self.label_13 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtGui.QFrame.Box)
        self.label_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtGui.QFrame.Box)
        self.label_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_33 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setFrameShape(QtGui.QFrame.Box)
        self.label_33.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 7, 0, 1, 1)
        self.label_35 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setFrameShape(QtGui.QFrame.Box)
        self.label_35.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_2.addWidget(self.label_35, 7, 3, 1, 1)
        self.label_ans3 = QtGui.QLabel(Dialog)
        self.label_ans3.setObjectName(_fromUtf8("label_ans3"))
        self.gridLayout_2.addWidget(self.label_ans3, 1, 1, 1, 1)
        self.label_ans5 = QtGui.QLabel(Dialog)
        self.label_ans5.setObjectName(_fromUtf8("label_ans5"))
        self.gridLayout_2.addWidget(self.label_ans5, 2, 1, 1, 1)
        self.label_ans7 = QtGui.QLabel(Dialog)
        self.label_ans7.setObjectName(_fromUtf8("label_ans7"))
        self.gridLayout_2.addWidget(self.label_ans7, 3, 1, 1, 1)
        self.label_ans9 = QtGui.QLabel(Dialog)
        self.label_ans9.setObjectName(_fromUtf8("label_ans9"))
        self.gridLayout_2.addWidget(self.label_ans9, 4, 1, 1, 1)
        self.label_ans11 = QtGui.QLabel(Dialog)
        self.label_ans11.setObjectName(_fromUtf8("label_ans11"))
        self.gridLayout_2.addWidget(self.label_ans11, 5, 1, 1, 1)
        self.label_ans13 = QtGui.QLabel(Dialog)
        self.label_ans13.setObjectName(_fromUtf8("label_ans13"))
        self.gridLayout_2.addWidget(self.label_ans13, 6, 1, 1, 1)
        self.label_ans15 = QtGui.QLabel(Dialog)
        self.label_ans15.setObjectName(_fromUtf8("label_ans15"))
        self.gridLayout_2.addWidget(self.label_ans15, 7, 1, 1, 1)
        self.label_ans4 = QtGui.QLabel(Dialog)
        self.label_ans4.setObjectName(_fromUtf8("label_ans4"))
        self.gridLayout_2.addWidget(self.label_ans4, 1, 4, 1, 1)
        self.label_ans6 = QtGui.QLabel(Dialog)
        self.label_ans6.setObjectName(_fromUtf8("label_ans6"))
        self.gridLayout_2.addWidget(self.label_ans6, 2, 4, 1, 1)
        self.label_ans8 = QtGui.QLabel(Dialog)
        self.label_ans8.setObjectName(_fromUtf8("label_ans8"))
        self.gridLayout_2.addWidget(self.label_ans8, 3, 4, 1, 1)
        self.label_ans10 = QtGui.QLabel(Dialog)
        self.label_ans10.setObjectName(_fromUtf8("label_ans10"))
        self.gridLayout_2.addWidget(self.label_ans10, 4, 4, 1, 1)
        self.label_ans12 = QtGui.QLabel(Dialog)
        self.label_ans12.setObjectName(_fromUtf8("label_ans12"))
        self.gridLayout_2.addWidget(self.label_ans12, 5, 4, 1, 1)
        self.label_ans14 = QtGui.QLabel(Dialog)
        self.label_ans14.setObjectName(_fromUtf8("label_ans14"))
        self.gridLayout_2.addWidget(self.label_ans14, 6, 4, 1, 1)
        self.label_ans16 = QtGui.QLabel(Dialog)
        self.label_ans16.setObjectName(_fromUtf8("label_ans16"))
        self.gridLayout_2.addWidget(self.label_ans16, 7, 4, 1, 1)
        self.combo_3 = QtGui.QComboBox(Dialog)
        self.combo_3.setEnabled(False)
        self.combo_3.setObjectName(_fromUtf8("combo_3"))
        self.combo_3.addItem(_fromUtf8(""))
        self.combo_3.addItem(_fromUtf8(""))
        self.combo_3.addItem(_fromUtf8(""))
        self.combo_3.addItem(_fromUtf8(""))
        self.combo_3.addItem(_fromUtf8(""))
        self.combo_3.addItem(_fromUtf8(""))
        self.combo_3.addItem(_fromUtf8(""))
        self.combo_3.addItem(_fromUtf8(""))
        self.combo_3.addItem(_fromUtf8(""))
        self.combo_3.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_3, 1, 2, 1, 1)
        self.label_ans1 = QtGui.QLabel(Dialog)
        self.label_ans1.setObjectName(_fromUtf8("label_ans1"))
        self.gridLayout_2.addWidget(self.label_ans1, 0, 1, 1, 1)
        self.combo_1 = QtGui.QComboBox(Dialog)
        self.combo_1.setEnabled(False)
        self.combo_1.setObjectName(_fromUtf8("combo_1"))
        self.combo_1.addItem(_fromUtf8(""))
        self.combo_1.addItem(_fromUtf8(""))
        self.combo_1.addItem(_fromUtf8(""))
        self.combo_1.addItem(_fromUtf8(""))
        self.combo_1.addItem(_fromUtf8(""))
        self.combo_1.addItem(_fromUtf8(""))
        self.combo_1.addItem(_fromUtf8(""))
        self.combo_1.addItem(_fromUtf8(""))
        self.combo_1.addItem(_fromUtf8(""))
        self.combo_1.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_1, 0, 2, 1, 1)
        self.combo_4 = QtGui.QComboBox(Dialog)
        self.combo_4.setEnabled(False)
        self.combo_4.setObjectName(_fromUtf8("combo_4"))
        self.combo_4.addItem(_fromUtf8(""))
        self.combo_4.addItem(_fromUtf8(""))
        self.combo_4.addItem(_fromUtf8(""))
        self.combo_4.addItem(_fromUtf8(""))
        self.combo_4.addItem(_fromUtf8(""))
        self.combo_4.addItem(_fromUtf8(""))
        self.combo_4.addItem(_fromUtf8(""))
        self.combo_4.addItem(_fromUtf8(""))
        self.combo_4.addItem(_fromUtf8(""))
        self.combo_4.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_4, 1, 5, 1, 1)
        self.label_ans2 = QtGui.QLabel(Dialog)
        self.label_ans2.setObjectName(_fromUtf8("label_ans2"))
        self.gridLayout_2.addWidget(self.label_ans2, 0, 4, 1, 1)
        self.combo_2 = QtGui.QComboBox(Dialog)
        self.combo_2.setEnabled(False)
        self.combo_2.setObjectName(_fromUtf8("combo_2"))
        self.combo_2.addItem(_fromUtf8(""))
        self.combo_2.addItem(_fromUtf8(""))
        self.combo_2.addItem(_fromUtf8(""))
        self.combo_2.addItem(_fromUtf8(""))
        self.combo_2.addItem(_fromUtf8(""))
        self.combo_2.addItem(_fromUtf8(""))
        self.combo_2.addItem(_fromUtf8(""))
        self.combo_2.addItem(_fromUtf8(""))
        self.combo_2.addItem(_fromUtf8(""))
        self.combo_2.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_2, 0, 5, 1, 1)
        self.combo_5 = QtGui.QComboBox(Dialog)
        self.combo_5.setEnabled(False)
        self.combo_5.setObjectName(_fromUtf8("combo_5"))
        self.combo_5.addItem(_fromUtf8(""))
        self.combo_5.addItem(_fromUtf8(""))
        self.combo_5.addItem(_fromUtf8(""))
        self.combo_5.addItem(_fromUtf8(""))
        self.combo_5.addItem(_fromUtf8(""))
        self.combo_5.addItem(_fromUtf8(""))
        self.combo_5.addItem(_fromUtf8(""))
        self.combo_5.addItem(_fromUtf8(""))
        self.combo_5.addItem(_fromUtf8(""))
        self.combo_5.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_5, 2, 2, 1, 1)
        self.combo_6 = QtGui.QComboBox(Dialog)
        self.combo_6.setEnabled(False)
        self.combo_6.setObjectName(_fromUtf8("combo_6"))
        self.combo_6.addItem(_fromUtf8(""))
        self.combo_6.addItem(_fromUtf8(""))
        self.combo_6.addItem(_fromUtf8(""))
        self.combo_6.addItem(_fromUtf8(""))
        self.combo_6.addItem(_fromUtf8(""))
        self.combo_6.addItem(_fromUtf8(""))
        self.combo_6.addItem(_fromUtf8(""))
        self.combo_6.addItem(_fromUtf8(""))
        self.combo_6.addItem(_fromUtf8(""))
        self.combo_6.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_6, 2, 5, 1, 1)
        self.combo_7 = QtGui.QComboBox(Dialog)
        self.combo_7.setEnabled(False)
        self.combo_7.setObjectName(_fromUtf8("combo_7"))
        self.combo_7.addItem(_fromUtf8(""))
        self.combo_7.addItem(_fromUtf8(""))
        self.combo_7.addItem(_fromUtf8(""))
        self.combo_7.addItem(_fromUtf8(""))
        self.combo_7.addItem(_fromUtf8(""))
        self.combo_7.addItem(_fromUtf8(""))
        self.combo_7.addItem(_fromUtf8(""))
        self.combo_7.addItem(_fromUtf8(""))
        self.combo_7.addItem(_fromUtf8(""))
        self.combo_7.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_7, 3, 2, 1, 1)
        self.combo_8 = QtGui.QComboBox(Dialog)
        self.combo_8.setEnabled(False)
        self.combo_8.setObjectName(_fromUtf8("combo_8"))
        self.combo_8.addItem(_fromUtf8(""))
        self.combo_8.addItem(_fromUtf8(""))
        self.combo_8.addItem(_fromUtf8(""))
        self.combo_8.addItem(_fromUtf8(""))
        self.combo_8.addItem(_fromUtf8(""))
        self.combo_8.addItem(_fromUtf8(""))
        self.combo_8.addItem(_fromUtf8(""))
        self.combo_8.addItem(_fromUtf8(""))
        self.combo_8.addItem(_fromUtf8(""))
        self.combo_8.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_8, 3, 5, 1, 1)
        self.combo_9 = QtGui.QComboBox(Dialog)
        self.combo_9.setEnabled(False)
        self.combo_9.setObjectName(_fromUtf8("combo_9"))
        self.combo_9.addItem(_fromUtf8(""))
        self.combo_9.addItem(_fromUtf8(""))
        self.combo_9.addItem(_fromUtf8(""))
        self.combo_9.addItem(_fromUtf8(""))
        self.combo_9.addItem(_fromUtf8(""))
        self.combo_9.addItem(_fromUtf8(""))
        self.combo_9.addItem(_fromUtf8(""))
        self.combo_9.addItem(_fromUtf8(""))
        self.combo_9.addItem(_fromUtf8(""))
        self.combo_9.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_9, 4, 2, 1, 1)
        self.combo_10 = QtGui.QComboBox(Dialog)
        self.combo_10.setEnabled(False)
        self.combo_10.setObjectName(_fromUtf8("combo_10"))
        self.combo_10.addItem(_fromUtf8(""))
        self.combo_10.addItem(_fromUtf8(""))
        self.combo_10.addItem(_fromUtf8(""))
        self.combo_10.addItem(_fromUtf8(""))
        self.combo_10.addItem(_fromUtf8(""))
        self.combo_10.addItem(_fromUtf8(""))
        self.combo_10.addItem(_fromUtf8(""))
        self.combo_10.addItem(_fromUtf8(""))
        self.combo_10.addItem(_fromUtf8(""))
        self.combo_10.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_10, 4, 5, 1, 1)
        self.combo_11 = QtGui.QComboBox(Dialog)
        self.combo_11.setEnabled(False)
        self.combo_11.setObjectName(_fromUtf8("combo_11"))
        self.combo_11.addItem(_fromUtf8(""))
        self.combo_11.addItem(_fromUtf8(""))
        self.combo_11.addItem(_fromUtf8(""))
        self.combo_11.addItem(_fromUtf8(""))
        self.combo_11.addItem(_fromUtf8(""))
        self.combo_11.addItem(_fromUtf8(""))
        self.combo_11.addItem(_fromUtf8(""))
        self.combo_11.addItem(_fromUtf8(""))
        self.combo_11.addItem(_fromUtf8(""))
        self.combo_11.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_11, 5, 2, 1, 1)
        self.combo_12 = QtGui.QComboBox(Dialog)
        self.combo_12.setEnabled(False)
        self.combo_12.setObjectName(_fromUtf8("combo_12"))
        self.combo_12.addItem(_fromUtf8(""))
        self.combo_12.addItem(_fromUtf8(""))
        self.combo_12.addItem(_fromUtf8(""))
        self.combo_12.addItem(_fromUtf8(""))
        self.combo_12.addItem(_fromUtf8(""))
        self.combo_12.addItem(_fromUtf8(""))
        self.combo_12.addItem(_fromUtf8(""))
        self.combo_12.addItem(_fromUtf8(""))
        self.combo_12.addItem(_fromUtf8(""))
        self.combo_12.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_12, 5, 5, 1, 1)
        self.combo_13 = QtGui.QComboBox(Dialog)
        self.combo_13.setEnabled(False)
        self.combo_13.setObjectName(_fromUtf8("combo_13"))
        self.combo_13.addItem(_fromUtf8(""))
        self.combo_13.addItem(_fromUtf8(""))
        self.combo_13.addItem(_fromUtf8(""))
        self.combo_13.addItem(_fromUtf8(""))
        self.combo_13.addItem(_fromUtf8(""))
        self.combo_13.addItem(_fromUtf8(""))
        self.combo_13.addItem(_fromUtf8(""))
        self.combo_13.addItem(_fromUtf8(""))
        self.combo_13.addItem(_fromUtf8(""))
        self.combo_13.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_13, 6, 2, 1, 1)
        self.combo_14 = QtGui.QComboBox(Dialog)
        self.combo_14.setEnabled(False)
        self.combo_14.setObjectName(_fromUtf8("combo_14"))
        self.combo_14.addItem(_fromUtf8(""))
        self.combo_14.addItem(_fromUtf8(""))
        self.combo_14.addItem(_fromUtf8(""))
        self.combo_14.addItem(_fromUtf8(""))
        self.combo_14.addItem(_fromUtf8(""))
        self.combo_14.addItem(_fromUtf8(""))
        self.combo_14.addItem(_fromUtf8(""))
        self.combo_14.addItem(_fromUtf8(""))
        self.combo_14.addItem(_fromUtf8(""))
        self.combo_14.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_14, 6, 5, 1, 1)
        self.combo_15 = QtGui.QComboBox(Dialog)
        self.combo_15.setEnabled(False)
        self.combo_15.setObjectName(_fromUtf8("combo_15"))
        self.combo_15.addItem(_fromUtf8(""))
        self.combo_15.addItem(_fromUtf8(""))
        self.combo_15.addItem(_fromUtf8(""))
        self.combo_15.addItem(_fromUtf8(""))
        self.combo_15.addItem(_fromUtf8(""))
        self.combo_15.addItem(_fromUtf8(""))
        self.combo_15.addItem(_fromUtf8(""))
        self.combo_15.addItem(_fromUtf8(""))
        self.combo_15.addItem(_fromUtf8(""))
        self.combo_15.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_15, 7, 2, 1, 1)
        self.combo_16 = QtGui.QComboBox(Dialog)
        self.combo_16.setEnabled(False)
        self.combo_16.setObjectName(_fromUtf8("combo_16"))
        self.combo_16.addItem(_fromUtf8(""))
        self.combo_16.addItem(_fromUtf8(""))
        self.combo_16.addItem(_fromUtf8(""))
        self.combo_16.addItem(_fromUtf8(""))
        self.combo_16.addItem(_fromUtf8(""))
        self.combo_16.addItem(_fromUtf8(""))
        self.combo_16.addItem(_fromUtf8(""))
        self.combo_16.addItem(_fromUtf8(""))
        self.combo_16.addItem(_fromUtf8(""))
        self.combo_16.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_16, 7, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 0, 1, 5)
        self.label4 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label4.setFont(font)
        self.label4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label4.setFrameShadow(QtGui.QFrame.Sunken)
        self.label4.setText(_fromUtf8(""))
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName(_fromUtf8("label4"))
        self.gridLayout.addWidget(self.label4, 3, 3, 1, 1)
        self.btn_end = QtGui.QPushButton(Dialog)
        self.btn_end.setEnabled(False)
        self.btn_end.setObjectName(_fromUtf8("btn_end"))
        self.gridLayout.addWidget(self.btn_end, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.spin_inv = QtGui.QSpinBox(Dialog)
        self.spin_inv.setMinimum(1)
        self.spin_inv.setMaximum(60)
        self.spin_inv.setSingleStep(1)
        self.spin_inv.setObjectName(_fromUtf8("spin_inv"))
        self.gridLayout.addWidget(self.spin_inv, 1, 3, 1, 1)
        self.combo_max = QtGui.QComboBox(Dialog)
        self.combo_max.setObjectName(_fromUtf8("combo_max"))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.combo_max.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.combo_max, 0, 3, 1, 1)
        self.label2 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label2.setFrameShadow(QtGui.QFrame.Sunken)
        self.label2.setText(_fromUtf8(""))
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.gridLayout.addWidget(self.label2, 3, 1, 1, 1)
        self.label3 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label3.setFont(font)
        self.label3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label3.setFrameShadow(QtGui.QFrame.Sunken)
        self.label3.setText(_fromUtf8(""))
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.gridLayout.addWidget(self.label3, 3, 2, 1, 1)
        self.btn_show = QtGui.QPushButton(Dialog)
        self.btn_show.setEnabled(False)
        self.btn_show.setObjectName(_fromUtf8("btn_show"))
        self.gridLayout.addWidget(self.btn_show, 2, 3, 1, 1)
        self.combo_min = QtGui.QComboBox(Dialog)
        self.combo_min.setObjectName(_fromUtf8("combo_min"))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.combo_min.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.combo_min, 0, 1, 1, 1)
        self.combo_cnt = QtGui.QComboBox(Dialog)
        self.combo_cnt.setObjectName(_fromUtf8("combo_cnt"))
        self.combo_cnt.addItem(_fromUtf8(""))
        self.combo_cnt.addItem(_fromUtf8(""))
        self.combo_cnt.addItem(_fromUtf8(""))
        self.combo_cnt.addItem(_fromUtf8(""))
        self.combo_cnt.addItem(_fromUtf8(""))
        self.combo_cnt.addItem(_fromUtf8(""))
        self.combo_cnt.addItem(_fromUtf8(""))
        self.combo_cnt.addItem(_fromUtf8(""))
        self.combo_cnt.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.combo_cnt, 1, 1, 1, 1)
        self.btn_con = QtGui.QPushButton(Dialog)
        self.btn_con.setEnabled(False)
        self.btn_con.setObjectName(_fromUtf8("btn_con"))
        self.gridLayout.addWidget(self.btn_con, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.btn_new, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.onBtnNew)
        QtCore.QObject.connect(self.btn_end, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.onBtnEnd)
        QtCore.QObject.connect(self.btn_con, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.onBtnCon)
        QtCore.QObject.connect(self.btn_show, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.onBtnShow)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Count Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Max Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Min Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Max Count", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_new.setText(QtGui.QApplication.translate("Dialog", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Dialog", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Dialog", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Dialog", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Dialog", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans3.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans5.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans7.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans9.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans11.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans13.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans15.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans4.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans6.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans8.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans10.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans12.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans14.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans16.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_3.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_3.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_3.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_3.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_3.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_3.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_3.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_3.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_3.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_3.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans1.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_1.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_1.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_1.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_1.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_1.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_1.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_1.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_1.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_1.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_1.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_4.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_4.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_4.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_4.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_4.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_4.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_4.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_4.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_4.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_4.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ans2.setText(QtGui.QApplication.translate("Dialog", "<font color=\"gray\">0</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_2.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_2.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_2.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_2.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_2.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_2.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_2.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_2.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_2.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_2.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_5.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_5.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_5.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_5.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_5.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_5.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_5.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_5.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_5.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_5.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_6.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_6.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_6.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_6.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_6.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_6.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_6.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_6.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_6.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_6.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_7.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_7.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_7.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_7.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_7.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_7.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_7.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_7.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_7.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_7.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_8.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_8.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_8.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_8.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_8.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_8.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_8.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_8.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_8.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_8.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_9.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_9.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_9.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_9.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_9.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_9.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_9.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_9.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_9.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_9.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_10.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_10.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_10.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_10.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_10.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_10.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_10.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_10.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_10.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_10.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_11.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_11.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_11.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_11.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_11.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_11.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_11.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_11.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_11.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_11.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_12.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_12.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_12.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_12.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_12.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_12.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_12.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_12.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_12.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_12.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_13.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_13.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_13.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_13.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_13.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_13.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_13.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_13.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_13.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_13.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_14.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_14.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_14.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_14.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_14.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_14.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_14.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_14.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_14.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_14.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_15.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_15.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_15.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_15.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_15.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_15.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_15.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_15.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_15.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_15.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_16.setItemText(0, QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_16.setItemText(1, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_16.setItemText(2, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_16.setItemText(3, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_16.setItemText(4, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_16.setItemText(5, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_16.setItemText(6, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_16.setItemText(7, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_16.setItemText(8, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_16.setItemText(9, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_end.setText(QtGui.QApplication.translate("Dialog", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(0, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(1, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(2, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(3, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(4, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(5, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(6, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(7, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(8, QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(9, QtGui.QApplication.translate("Dialog", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(10, QtGui.QApplication.translate("Dialog", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(11, QtGui.QApplication.translate("Dialog", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(12, QtGui.QApplication.translate("Dialog", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(13, QtGui.QApplication.translate("Dialog", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_max.setItemText(14, QtGui.QApplication.translate("Dialog", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_show.setText(QtGui.QApplication.translate("Dialog", "Show Answer", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(0, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(1, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(2, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(3, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(4, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(5, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(6, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(7, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(8, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(9, QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(10, QtGui.QApplication.translate("Dialog", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(11, QtGui.QApplication.translate("Dialog", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(12, QtGui.QApplication.translate("Dialog", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(13, QtGui.QApplication.translate("Dialog", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_min.setItemText(14, QtGui.QApplication.translate("Dialog", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_cnt.setItemText(0, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_cnt.setItemText(1, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_cnt.setItemText(2, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_cnt.setItemText(3, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_cnt.setItemText(4, QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_cnt.setItemText(5, QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_cnt.setItemText(6, QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_cnt.setItemText(7, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_cnt.setItemText(8, QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_con.setText(QtGui.QApplication.translate("Dialog", "Continue", None, QtGui.QApplication.UnicodeUTF8))

